name: dpo-generation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # or 12.1 depending on your CUDA version
  - pip
  - pip:
    - transformers>=4.37.0
    - pillow>=9.0.0
    - numpy>=1.21.0
    - qwen-vl-utils
    - accelerate>=0.20.0
    - datasets
    - sentencepiece
    - protobuf
